// <auto-generated>
/*
 * OpenAPI Petstore
 *
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenAPIClientUtils = Org.OpenAPITools.Client.ClientUtils;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// MixLog
    /// </summary>
    public partial class MixLog : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MixLog" /> class.
        /// </summary>
        /// <param name="description">description</param>
        /// <param name="formulaVersionDate">formulaVersionDate</param>
        /// <param name="id">id</param>
        /// <param name="mixDate">mixDate</param>
        /// <param name="totalOverPoors">totalOverPoors</param>
        /// <param name="totalRecalculations">totalRecalculations</param>
        /// <param name="totalSkips">totalSkips</param>
        /// <param name="totalUnderPours">totalUnderPours</param>
        /// <param name="batchNumber">batchNumber</param>
        /// <param name="brandCode">BrandCode is only required for non-color mixes</param>
        /// <param name="brandId">BrandId is only required for color mixes</param>
        /// <param name="brandName">BrandName is only required for color mixes</param>
        /// <param name="categoryCode">CategoryCode is not used anymore</param>
        /// <param name="color">Color is only required for color mixes</param>
        /// <param name="colorDescription">colorDescription</param>
        /// <param name="comment">comment</param>
        /// <param name="commercialProductCode">commercialProductCode</param>
        /// <param name="country">country</param>
        /// <param name="createdBy">createdBy</param>
        /// <param name="createdByFirstName">createdByFirstName</param>
        /// <param name="createdByLastName">createdByLastName</param>
        /// <param name="deltaECalculationRepaired">deltaECalculationRepaired</param>
        /// <param name="deltaECalculationSprayout">deltaECalculationSprayout</param>
        /// <param name="ownColorVariantNumber">ownColorVariantNumber</param>
        /// <param name="primerProductId">primerProductId</param>
        /// <param name="productId">ProductId is only required for color mixes</param>
        /// <param name="productLineCode">ProductLineCode is only required for color mixes</param>
        /// <param name="productName">ProductName is only required for color mixes</param>
        /// <param name="selectedVersionIndex">selectedVersionIndex</param>
        /// <param name="shopId">shopId</param>
        /// <param name="someCode">SomeCode is only required for color mixes</param>
        /// <param name="totalPrice">totalPrice</param>
        [JsonConstructor]
        public MixLog(string description, DateTime formulaVersionDate, Guid id, DateTime mixDate, int totalOverPoors, int totalRecalculations, int totalSkips, int totalUnderPours, Option<string> batchNumber = default, Option<string> brandCode = default, Option<string> brandId = default, Option<string> brandName = default, Option<string> categoryCode = default, Option<string> color = default, Option<string> colorDescription = default, Option<string> comment = default, Option<string> commercialProductCode = default, Option<string> country = default, Option<string> createdBy = default, Option<string> createdByFirstName = default, Option<string> createdByLastName = default, Option<string> deltaECalculationRepaired = default, Option<string> deltaECalculationSprayout = default, Option<int?> ownColorVar